### ISSUE TITLE
entityframework-nsubstitute not compatible with Nsubstitute 4+

### ISSUE THREAD

**Issue by PeteW** [huysentruitw/entity-framework-core-mock#14]
Yields a MissingMethodException Nsubstitute.Arg.Any(..)
I found that the error message is avoided when i downgrade from NSubstitute 4.0.0 to 3.1.0

**Comment by huysentruitw** [comment]
In version 1.0.0.23+ I've updated all NuGet packages (including NSubstitute to 4.0.0), but I didn't see the exception you're talking about. Anyway, can you try that version and see if it fixes your issue?

If not, please provide a proper test case. Thanks!

**Comment by huysentruitw** [comment]
Closing this issue for now, feel free to reopen if the issue persists.
