### ISSUE TITLE
modelBuilder.ApplyConfiguration

### ISSUE THREAD

**Issue by pfaustinopt** [huysentruitw/entity-framework-core-mock#18]
Hey,

Is it possible to use the `IEntityTypeConfiguration` instead of this?
```
public class User
{
    [Key, Column(Order = 0)]
    public Guid Id { get; set; }

    public string FullName { get; set; }
}
```

**Comment by huysentruitw** [comment]
Little late to the party, but you can probably use the same solution as I'm talking about [here](https://github.com/huysentruitw/entity-framework-core-mock/issues/19#issuecomment-523125640)
