### ISSUE TITLE
[Enhancement] Nuget package

### ISSUE THREAD

**Issue by tiagodenoronha** [huysentruitw/entity-framework-core-mock#2]
It would be very useful to use this as a nuget package so further testing can be made :)

**Comment by huysentruitw** [comment]
Hi @tiagodenoronha,

what do you mean exactly? The library is available as NuGet packages, see the readme at https://github.com/huysentruitw/entity-framework-core-mock

**Comment by tiagodenoronha** [comment]
I have no idea how I missed this... clearly it's time to take a break and get some sleep :)

Thanks! I'll give it a whirl on my project and then give you some feedback! :)
