### ISSUE TITLE
Couldn't instantiate proxy of class

### ISSUE THREAD

**Issue by tiagodenoronha** [huysentruitw/entity-framework-core-mock#3]
Hey, i'm giving the nuget package a try and encountered this exception, was it something I did on my side?

![image](https://user-images.githubusercontent.com/27889458/47051339-caf52680-d19b-11e8-8a96-e36f2ef31892.png)

**Comment by huysentruitw** [comment]
Can I see the DefaultOptions declaration?

**Comment by tiagodenoronha** [comment]
It's the same as the readme:

 `public DbContextOptions DefaultOptions{ get; } = new DbContextOptionsBuilder().Options;`

**Comment by huysentruitw** [comment]
Can you try `public DbContextOptions<PlantsContext> DefaultOptions{ get; } = new DbContextOptionsBuilder<PlantsContext>().Options;` ?

**Comment by huysentruitw** [comment]
You'll need to post more context I'm affairs.

**Comment by huysentruitw** [comment]
When changing `AsEnumerable()` in the service to `ToArray()`, it seems to work, so I'll have to dig into the source, probably `AsEnumerable()` is just not mapped.

For the test `Plants_GetAll_ReturnsOk`, you need to initialize the DbSet:

    dbContextMock.CreateDbSetMock(x => x.Plant);

**Comment by tiagodenoronha** [comment]
Hmm gotcha, i'll change the method to ToArray for now :)

The first test I hadn't tried it yet :b
I'll close this issue and open up a new one with "Map AsEnumerable" so you can track it better.
