### ISSUE TITLE
Mock DbQuery

### ISSUE THREAD

**Issue by cbjpdev** [huysentruitw/entity-framework-core-mock#5]
How to mock DbQuery in this library?
I have some inline sql and few views used in efcore.
dbContextMock.CreateDbSetMock only accepts DbSet

**Comment by huysentruitw** [comment]
Hi, can you please post a minimal example code of your usage?

**Comment by cbjpdev** [comment]
Hi, Currently I don't have code with me, But its based on content below. It a new feature in EFcore2.1
https://docs.microsoft.com/en-us/ef/core/modeling/query-types

We have existing views in database and this is how we are querying views.

`protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    modelBuilder.Query<BlogPostsCount>().ToView("View_BlogPostCounts");
}`

`public int GetMethod()
{
  return db.BlogPostCounts.ToList()
}`

**Comment by huysentruitw** [comment]
I've added support for DbQuery in v1.0.0.11, please re-test.

**Comment by cbjpdev** [comment]
Hi Thanks for fix, 
It is working for below.
`public async Task<VW_Boats> GetByIdAsync(string b_id)
{
	return await _boatcontext.VW_Boats.SingleOrDefaultAsync(x => x.b_id == b_id);
}`

But giving error for below.
public async Task<VW_Boats> GetByIdAsync(string b_id)
{
	return await _boatcontext.Query<VW_Boats>().Where(x => x.b_id == b_id).FirstOrDefaultAsync();
}

`: 'One or more errors occurred. (The provider for the source IQueryable doesn't implement IAsyncQueryProvider. Only providers that implement IEntityQueryProvider can be used for Entity Framework asynchronous operations.)'`

**Comment by cbjpdev** [comment]
More scenarios:

When we use orderby, it gives this error
`---- System.InvalidOperationException : The source IQueryable doesn't implement IAsyncEnumerable<re_analytics_service.Models.Deal.VwrpProperties>. Only sources that implement IAsyncEnumerable can be used for Entity Framework asynchronous operations.`

usage
`List<VW_Boats> list = await _dbContext.VW_Boats
						.Where(x => x.b_id == b_id)
						//.OrderByDescending(x => x.last_update_dt)
						.ToListAsync();`

**Comment by huysentruitw** [comment]
I'm puzzled, because those are exactly the interfaces I'm implementing [here](https://github.com/huysentruitw/entity-framework-core-mock/blob/master/src/EntityFrameworkCoreMock.Shared/DbAsyncEnumerable.cs) and [here](https://github.com/huysentruitw/entity-framework-core-mock/blob/master/src/EntityFrameworkCoreMock.Shared/DbAsyncQueryProvider.cs).

Are you sure your project and the test project are using the same version of NuGet dependencies?

**Comment by cbjpdev** [comment]
yeah, same dependencies. Issue is not coming at your end? cannot reproduce?

**Comment by huysentruitw** [comment]
Please re-test with v1.0.0.12

**Comment by cbjpdev** [comment]
Works!!!. Thank you very much.

**Comment by huysentruitw** [comment]
thanks for bringing this up 🎉
