### ISSUE TITLE
Mock _dbContext.Database, ExecuteSqlCommandAsync in EFCore

### ISSUE THREAD

**Issue by cbjpdev** [huysentruitw/entity-framework-core-mock#7]
Hi, 

I want to mock  ExecuteSqlCommandAsync  and ExecuteReader. We have to use these due to specific reason. This may not be a feature request. Please explain me how to achieve mocking these?

case 1:
using (var command = _dbContext.Database.GetDbConnection().CreateCommand())
{
	command.CommandText = string.Format("select NEXT VALUE FOR {0}", sequenceName);
	_dbContext.Database.OpenConnection();
	using (var result = command.ExecuteReader())
	{
		if (result.Read())
		{
			seqValue = result[0].ToString();
		}
	}
}

case 2:
createdCount = await _reapContext.Database.ExecuteSqlCommandAsync(createSql);

**Comment by huysentruitw** [comment]
I think you need to use an integration test to cover that. There's no use in mocking a reader line that in my opinion.

**Comment by cbjpdev** [comment]
Yes, that would be the option. Anyway I added few interfaces and mocking these. No blocker for the moment. Can test these in the integration testing.

**Comment by huysentruitw** [comment]
Ok I'll close it for now. If you have any specific request regarding this which could benifit the library, feel free to reopen.
